package com.carcassonne.gameserver.tempB;

public class Card {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.top_edge_id
     *
     * @mbg.generated
     */
    private String topEdgeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.bot_edge_id
     *
     * @mbg.generated
     */
    private String botEdgeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.lef_edge_id
     *
     * @mbg.generated
     */
    private String lefEdgeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.rig_edge_id
     *
     * @mbg.generated
     */
    private String rigEdgeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.picture_url
     *
     * @mbg.generated
     */
    private String pictureUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.id
     *
     * @return the value of card.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.id
     *
     * @param id the value for card.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.top_edge_id
     *
     * @return the value of card.top_edge_id
     *
     * @mbg.generated
     */
    public String getTopEdgeId() {
        return topEdgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.top_edge_id
     *
     * @param topEdgeId the value for card.top_edge_id
     *
     * @mbg.generated
     */
    public void setTopEdgeId(String topEdgeId) {
        this.topEdgeId = topEdgeId == null ? null : topEdgeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.bot_edge_id
     *
     * @return the value of card.bot_edge_id
     *
     * @mbg.generated
     */
    public String getBotEdgeId() {
        return botEdgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.bot_edge_id
     *
     * @param botEdgeId the value for card.bot_edge_id
     *
     * @mbg.generated
     */
    public void setBotEdgeId(String botEdgeId) {
        this.botEdgeId = botEdgeId == null ? null : botEdgeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.lef_edge_id
     *
     * @return the value of card.lef_edge_id
     *
     * @mbg.generated
     */
    public String getLefEdgeId() {
        return lefEdgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.lef_edge_id
     *
     * @param lefEdgeId the value for card.lef_edge_id
     *
     * @mbg.generated
     */
    public void setLefEdgeId(String lefEdgeId) {
        this.lefEdgeId = lefEdgeId == null ? null : lefEdgeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.rig_edge_id
     *
     * @return the value of card.rig_edge_id
     *
     * @mbg.generated
     */
    public String getRigEdgeId() {
        return rigEdgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.rig_edge_id
     *
     * @param rigEdgeId the value for card.rig_edge_id
     *
     * @mbg.generated
     */
    public void setRigEdgeId(String rigEdgeId) {
        this.rigEdgeId = rigEdgeId == null ? null : rigEdgeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.picture_url
     *
     * @return the value of card.picture_url
     *
     * @mbg.generated
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.picture_url
     *
     * @param pictureUrl the value for card.picture_url
     *
     * @mbg.generated
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }
}