package com.carcassonne.gameserver.tempB;

public class Edge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edge.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edge.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edge.connection
     *
     * @mbg.generated
     */
    private String connection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edge.position
     *
     * @mbg.generated
     */
    private String position;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edge.id
     *
     * @return the value of edge.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edge.id
     *
     * @param id the value for edge.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edge.type
     *
     * @return the value of edge.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edge.type
     *
     * @param type the value for edge.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edge.connection
     *
     * @return the value of edge.connection
     *
     * @mbg.generated
     */
    public String getConnection() {
        return connection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edge.connection
     *
     * @param connection the value for edge.connection
     *
     * @mbg.generated
     */
    public void setConnection(String connection) {
        this.connection = connection == null ? null : connection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edge.position
     *
     * @return the value of edge.position
     *
     * @mbg.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edge.position
     *
     * @param position the value for edge.position
     *
     * @mbg.generated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }
}