package com.carcassonne.gameserver.tempB;

import java.util.Date;

public class GameResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_result.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_result.users
     *
     * @mbg.generated
     */
    private String users;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_result.start_info
     *
     * @mbg.generated
     */
    private String startInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_result.end_info
     *
     * @mbg.generated
     */
    private String endInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_result.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_result.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_result.id
     *
     * @return the value of game_result.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_result.id
     *
     * @param id the value for game_result.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_result.users
     *
     * @return the value of game_result.users
     *
     * @mbg.generated
     */
    public String getUsers() {
        return users;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_result.users
     *
     * @param users the value for game_result.users
     *
     * @mbg.generated
     */
    public void setUsers(String users) {
        this.users = users == null ? null : users.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_result.start_info
     *
     * @return the value of game_result.start_info
     *
     * @mbg.generated
     */
    public String getStartInfo() {
        return startInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_result.start_info
     *
     * @param startInfo the value for game_result.start_info
     *
     * @mbg.generated
     */
    public void setStartInfo(String startInfo) {
        this.startInfo = startInfo == null ? null : startInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_result.end_info
     *
     * @return the value of game_result.end_info
     *
     * @mbg.generated
     */
    public String getEndInfo() {
        return endInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_result.end_info
     *
     * @param endInfo the value for game_result.end_info
     *
     * @mbg.generated
     */
    public void setEndInfo(String endInfo) {
        this.endInfo = endInfo == null ? null : endInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_result.start_time
     *
     * @return the value of game_result.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_result.start_time
     *
     * @param startTime the value for game_result.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_result.end_time
     *
     * @return the value of game_result.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_result.end_time
     *
     * @param endTime the value for game_result.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}