package com.carcassonne.gameserver.tempB;

public class Log {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.game_record_id
     *
     * @mbg.generated
     */
    private Integer gameRecordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.users
     *
     * @mbg.generated
     */
    private String users;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.game_info
     *
     * @mbg.generated
     */
    private String gameInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.game_record_id
     *
     * @return the value of log.game_record_id
     *
     * @mbg.generated
     */
    public Integer getGameRecordId() {
        return gameRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.game_record_id
     *
     * @param gameRecordId the value for log.game_record_id
     *
     * @mbg.generated
     */
    public void setGameRecordId(Integer gameRecordId) {
        this.gameRecordId = gameRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.users
     *
     * @return the value of log.users
     *
     * @mbg.generated
     */
    public String getUsers() {
        return users;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.users
     *
     * @param users the value for log.users
     *
     * @mbg.generated
     */
    public void setUsers(String users) {
        this.users = users == null ? null : users.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.game_info
     *
     * @return the value of log.game_info
     *
     * @mbg.generated
     */
    public String getGameInfo() {
        return gameInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.game_info
     *
     * @param gameInfo the value for log.game_info
     *
     * @mbg.generated
     */
    public void setGameInfo(String gameInfo) {
        this.gameInfo = gameInfo == null ? null : gameInfo.trim();
    }
}