package com.carcassonne.gameserver.tempB;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.accoutNum
     *
     * @mbg.generated
     */
    private String accoutnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.identity
     *
     * @mbg.generated
     */
    private String identity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.joinmeetingid
     *
     * @mbg.generated
     */
    private String joinmeetingid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.joinsmallforumid
     *
     * @mbg.generated
     */
    private String joinsmallforumid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.accoutNum
     *
     * @return the value of user.accoutNum
     *
     * @mbg.generated
     */
    public String getAccoutnum() {
        return accoutnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.accoutNum
     *
     * @param accoutnum the value for user.accoutNum
     *
     * @mbg.generated
     */
    public void setAccoutnum(String accoutnum) {
        this.accoutnum = accoutnum == null ? null : accoutnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.identity
     *
     * @return the value of user.identity
     *
     * @mbg.generated
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.identity
     *
     * @param identity the value for user.identity
     *
     * @mbg.generated
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.joinmeetingid
     *
     * @return the value of user.joinmeetingid
     *
     * @mbg.generated
     */
    public String getJoinmeetingid() {
        return joinmeetingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.joinmeetingid
     *
     * @param joinmeetingid the value for user.joinmeetingid
     *
     * @mbg.generated
     */
    public void setJoinmeetingid(String joinmeetingid) {
        this.joinmeetingid = joinmeetingid == null ? null : joinmeetingid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.joinsmallforumid
     *
     * @return the value of user.joinsmallforumid
     *
     * @mbg.generated
     */
    public String getJoinsmallforumid() {
        return joinsmallforumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.joinsmallforumid
     *
     * @param joinsmallforumid the value for user.joinsmallforumid
     *
     * @mbg.generated
     */
    public void setJoinsmallforumid(String joinsmallforumid) {
        this.joinsmallforumid = joinsmallforumid == null ? null : joinsmallforumid.trim();
    }
}