package com.carcassonne.gameserver.mapper;


import com.carcassonne.gameserver.bean.Edge;

public interface EdgeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edge
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edge
     *
     * @mbg.generated
     */
    int insert(Edge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edge
     *
     * @mbg.generated
     */
    int insertSelective(Edge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edge
     *
     * @mbg.generated
     */
    Edge selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edge
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Edge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edge
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Edge record);
}