package com.carcassonne.gameserver.mapper;


import com.carcassonne.gameserver.bean.GameResult;

public interface GameResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_result
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_result
     *
     * @mbg.generated
     */
    int insert(GameResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_result
     *
     * @mbg.generated
     */
    int insertSelective(GameResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_result
     *
     * @mbg.generated
     */
    GameResult selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GameResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GameResult record);
}